name: Product Released workflow
on:
  pull_request:
    branches: [ master ]
    types:
      - closed
      - labeled

jobs:
  Deploy_and_Build:
    if: (github.event.pull_request.merged == true) && contains(github.event.pull_request.labels.*.name, 'released')
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
      - name: Dev repo build and test
        run: echo "Dev repo build"

  Unit_Testing:
    needs: Deploy_and_Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
      - name: Dev repo build and test
        run: echo "Unit test done"

  Smoke_Testing:
    needs: Unit_Testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
      - name: Setup Java environment
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Getting Test repo
        uses: actions/checkout@master
        with:
          repository: EVNPOC/epam-poc-playwright
          path: ./tests
      - name: Build Test repo
        run: mvn -B install -D skipTests --no-transfer-progress
        working-directory: tests
      - name: Install Playwright
        run: mvn exec:java -e -D exec.mainClass=com.microsoft.playwright.CLI -D exec.args="install --with-deps"
        working-directory: tests
      - name: Run tests
        run: xvfb-run mvn test -Dsurefire.suiteXmlFiles="testNG/smoke.xml" -Dgroups=smoke
        working-directory: tests
      - name: Export Test result
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: allure-results
          path: tests/allure-results/

  Triggering_Regression_Testing:
    needs: Smoke_Testing
    runs-on: ubuntu-latest
    steps:
      - name: trigger Regression test
        uses: convictional/trigger-workflow-and-wait@v1.6.1
        with:
          owner: EVNPOC
          repo: epam-poc-playwright
          github_token: ${{ secrets.PAT_TOKEN }}
          workflow_file_name: release.workflow.yml
          ref: master
          wait_workflow: false