name: Integration with Test repo
on:
  pull_request:
    branches: [ master ]
    types:
      - closed
      - labeled

jobs:
  integration:
    if: github.event.pull_request.merged == true && github.event.label.name == 'released'
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: check check
        run: echo "hello world, this is CICD -"
      # - name: Build & Install
      #   run: mvn -B install -D skipTests --no-transfer-progress
      # - name: Install Playwright
      #   run: mvn exec:java -e -D exec.mainClass=com.microsoft.playwright.CLI -D exec.args="install --with-deps"
      # - name: Run tests
      #   run: xvfb-run mvn test -Dsurefire.suiteXmlFiles="testNG/smoke.xml" -Dgroups=smoke
      # - name: Archive code coverage results
      #   uses: actions/upload-artifact@v3
      #   if: always()
      #   with:
      #     name: allure-results
      #     path: allure-results/